# Generated by Django 3.1.5 on 2021-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('success', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
