# Generated by Django 3.1.5 on 2021-04-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='security_answer',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='genericuser',
            name='security_answer',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='security_answer',
            field=models.CharField(default='', max_length=60),
        ),
    ]
