# Generated by Django 3.1.5 on 2021-02-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverUser',
            new_name='Drivers',
        ),
    ]
