# Generated by Django 3.1.5 on 2021-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_genericuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
