# Generated by Django 3.1.5 on 2021-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210211_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
