# Generated by Django 3.1.5 on 2021-02-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210211_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_Hist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('sponsor_username', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=300)),
            ],
        ),
    ]
