# Generated by Django 3.1.5 on 2021-02-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_point_hist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point_Hist',
            new_name='PointHist',
        ),
    ]
