# Generated by Django 3.1.5 on 2021-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210216_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('desc', models.CharField(max_length=2000)),
                ('idNum', models.IntegerField(default=1)),
            ],
        ),
    ]
