# Generated by Django 3.1.7 on 2021-02-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='sponsor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phone_num',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_company',
            field=models.CharField(default='', max_length=30),
        ),
    ]
