# Generated by Django 3.1.5 on 2021-03-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210223_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='static/profile_photos'),
        ),
    ]
