# Generated by Django 3.1.7 on 2021-04-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210310_0128'),
        ('users', '0016_auto_20210304_0604'),
    ]

    operations = [
    ]
