# Generated by Django 3.1.5 on 2021-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sponsor_company',
            field=models.CharField(default='', max_length=30),
        ),
    ]
