# Generated by Django 3.1.7 on 2021-04-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20210401_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='security_answer',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='security_question',
            field=models.CharField(default='', max_length=60),
        ),
    ]
