# Generated by Django 3.1.7 on 2021-04-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210408_1957'),
        ('users', '0018_application_sponsor_company'),
    ]

    operations = [
    ]
