# Generated by Django 3.1.7 on 2021-04-13 18:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_20210413_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=50, size=[1920, 1080], upload_to='profile_photos'),
        ),
    ]
