# Generated by Django 3.1.5 on 2021-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_pointhist_sponsor_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_company', models.CharField(default='', max_length=30)),
                ('sponsor_username', models.CharField(default='', max_length=30)),
                ('driver', models.CharField(max_length=30)),
                ('driver_points', models.IntegerField(default=0)),
                ('price_scalar', models.FloatField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='priceRaw',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='sponsor_company',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_items_per_page',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_last_search',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_sort_on',
            field=models.CharField(default='name', max_length=7),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='catalog_sort_order',
            field=models.CharField(default='up', max_length=4),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_items_per_page',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_last_search',
            field=models.CharField(default='candle', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_sort_on',
            field=models.CharField(default='created', max_length=7),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='list_sort_order',
            field=models.CharField(default='up', max_length=4),
        ),
    ]
