# Generated by Django 3.2 on 2021-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210410_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='point_change_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='driver_vicarious',
            field=models.CharField(default='', max_length=30),
        ),
    ]
