# Generated by Django 3.1.7 on 2021-04-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210413_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuser',
            name='security_answer',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='genericuser',
            name='security_question',
            field=models.CharField(default='', max_length=60),
        ),
    ]
