# Generated by Django 3.1.5 on 2021-04-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210412_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='sponsor_username',
        ),
    ]
