# Generated by Django 3.1.5 on 2021-04-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_sponsorship_sponsor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='sponsor',
        ),
    ]
