# Generated by Django 3.1.5 on 2021-04-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_application_sponsor'),
        ('users', '0023_driverorder'),
    ]

    operations = [
    ]
