# Generated by Django 3.1.5 on 2021-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_merge_20210415_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhist',
            name='date',
            field=models.DateField(max_length=30),
        ),
    ]
