# Generated by Django 3.1.5 on 2021-04-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210415_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhist',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
