# Generated by Django 3.1.6 on 2021-04-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210415_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorder',
            name='orderStatus',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='driverorder',
            name='sponsor_company',
            field=models.CharField(default='', max_length=30),
        ),
    ]
