# Generated by Django 3.1.7 on 2021-04-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210415_1802'),
        ('users', '0022_auto_20210413_1954'),
    ]

    operations = [
    ]
