# Generated by Django 3.1.5 on 2021-04-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_merge_20210418_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericuser',
            name='security_answer',
        ),
    ]
