# Generated by Django 3.1.5 on 2021-04-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_genericuser_security_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='security_answer',
        ),
    ]
